const pools = [
  {
    id: 'pool-1',
    name: 'US East Pool',
    hashrateTHs: 830.5,
    activeWorkers: 1240,
    rejectRate: 0.012,
    status: 'online',
  },
  {
    id: 'pool-2',
    name: 'EU Central Pool',
    hashrateTHs: 460.3,
    activeWorkers: 876,
    rejectRate: 0.045,
    status: 'degraded',
    details: { last24hRevenueBTC: 0.021, uptimePercent: 98.65, location: 'Frankfurt, Germany', feePercent: 1.2 },
  },
  {
    id: 'pool-3',
    name: 'Asia South Pool',
    hashrateTHs: 390.1,
    activeWorkers: 932,
    rejectRate: 0.007,
    status: 'online',
    details: { last24hRevenueBTC: 0.032, uptimePercent: 99.91, location: 'Singapore', feePercent: 0.8 },
  },
  {
    id: 'pool-4',
    name: 'Africa North Pool',
    hashrateTHs: 210.8,
    activeWorkers: 512,
    rejectRate: 0.035,
    status: 'offline',
    details: { last24hRevenueBTC: 0.015, uptimePercent: 94.3, location: 'Cairo, Egypt', feePercent: 1.5 },
  },
  {
    id: 'pool-5',
    name: 'South America Pool',
    hashrateTHs: 312.6,
    activeWorkers: 654,
    rejectRate: 0.018,
    status: 'degraded',
    details: { last24hRevenueBTC: 0.025, uptimePercent: 97.2, location: 'São Paulo, Brazil', feePercent: 1.1 },
  },
  {
    id: 'pool-6',
    name: 'Canada West Pool',
    hashrateTHs: 290.3,
    activeWorkers: 722,
    rejectRate: 0.009,
    status: 'online',
    details: { last24hRevenueBTC: 0.028, uptimePercent: 99.2, location: 'Vancouver, Canada', feePercent: 0.9 },
  },
  {
    id: 'pool-7',
    name: 'Russia Siberia Pool',
    hashrateTHs: 550.9,
    activeWorkers: 1175,
    rejectRate: 0.02,
    status: 'offline',
    details: { last24hRevenueBTC: 0.03, uptimePercent: 92.4, location: 'Novosibirsk, Russia', feePercent: 1.4 },
  },
  {
    id: 'pool-8',
    name: 'India West Pool',
    hashrateTHs: 342.7,
    activeWorkers: 689,
    rejectRate: 0.014,
    status: 'online',
    details: { last24hRevenueBTC: 0.026, uptimePercent: 98.8, location: 'Mumbai, India', feePercent: 1.0 },
  },
  {
    id: 'pool-9',
    name: 'China Inner Mongolia Pool',
    hashrateTHs: 1020.4,
    activeWorkers: 2021,
    rejectRate: 0.005,
    status: 'online',
    details: { last24hRevenueBTC: 0.045, uptimePercent: 99.9, location: 'Ordos, China', feePercent: 0.6 },
  },
  {
    id: 'pool-10',
    name: 'Japan Tokyo Pool',
    hashrateTHs: 370.2,
    activeWorkers: 780,
    rejectRate: 0.011,
    status: 'degraded',
    details: { last24hRevenueBTC: 0.029, uptimePercent: 96.5, location: 'Tokyo, Japan', feePercent: 1.2 },
  },
  {
    id: 'pool-11',
    name: 'UK London Pool',
    hashrateTHs: 488.8,
    activeWorkers: 905,
    rejectRate: 0.013,
    status: 'online',
    details: { last24hRevenueBTC: 0.033, uptimePercent: 99.1, location: 'London, UK', feePercent: 1.0 },
  },
  {
    id: 'pool-12',
    name: 'Australia East Pool',
    hashrateTHs: 275.4,
    activeWorkers: 601,
    rejectRate: 0.017,
    status: 'degraded',
    details: { last24hRevenueBTC: 0.023, uptimePercent: 95.7, location: 'Sydney, Australia', feePercent: 1.3 },
  },
  {
    id: 'pool-13',
    name: 'Norway Arctic Pool',
    hashrateTHs: 305.7,
    activeWorkers: 500,
    rejectRate: 0.008,
    status: 'online',
    details: { last24hRevenueBTC: 0.031, uptimePercent: 99.7, location: 'Tromsø, Norway', feePercent: 0.7 },
  },
  {
    id: 'pool-14',
    name: 'Brazil North Pool',
    hashrateTHs: 198.3,
    activeWorkers: 430,
    rejectRate: 0.027,
    status: 'offline',
    details: { last24hRevenueBTC: 0.019, uptimePercent: 90.4, location: 'Manaus, Brazil', feePercent: 1.5 },
  },
  {
    id: 'pool-15',
    name: 'South Korea Pool',
    hashrateTHs: 445.5,
    activeWorkers: 890,
    rejectRate: 0.010,
    status: 'online',
    details: { last24hRevenueBTC: 0.034, uptimePercent: 99.0, location: 'Seoul, South Korea', feePercent: 0.9 },
  },
  {
    id: 'pool-16',
    name: 'Mexico City Pool',
    hashrateTHs: 225.2,
    activeWorkers: 510,
    rejectRate: 0.024,
    status: 'degraded',
    details: { last24hRevenueBTC: 0.022, uptimePercent: 96.1, location: 'Mexico City, Mexico', feePercent: 1.2 },
  },
  {
    id: 'pool-17',
    name: 'Germany Frankfurt Pool',
    hashrateTHs: 495.7,
    activeWorkers: 942,
    rejectRate: 0.006,
    status: 'online',
    details: { last24hRevenueBTC: 0.036, uptimePercent: 99.6, location: 'Frankfurt, Germany', feePercent: 0.95 },
  },
  {
    id: 'pool-18',
    name: 'Turkey Istanbul Pool',
    hashrateTHs: 312.5,
    activeWorkers: 721,
    rejectRate: 0.022,
    status: 'offline',
    details: { last24hRevenueBTC: 0.02, uptimePercent: 92.8, location: 'Istanbul, Turkey', feePercent: 1.4 },
  },
  {
    id: 'pool-19',
    name: 'Spain Madrid Pool',
    hashrateTHs: 276.9,
    activeWorkers: 567,
    rejectRate: 0.019,
    status: 'degraded',
    details: { last24hRevenueBTC: 0.025, uptimePercent: 95.8, location: 'Madrid, Spain', feePercent: 1.0 },
  },
  {
    id: 'pool-20',
    name: 'Argentina Buenos Aires Pool',
    hashrateTHs: 158.6,
    activeWorkers: 398,
    rejectRate: 0.03,
    status: 'offline',
    details: { last24hRevenueBTC: 0.017, uptimePercent: 89.7, location: 'Buenos Aires, Argentina', feePercent: 1.6 },
  },
];

module.exports = pools;